# Generated by Django 4.1.3 on 2022-11-29 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoloc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='yaw',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
