# Generated by Django 4.1.3 on 2022-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('voice_message', models.CharField(default='You have reached ', max_length=200)),
            ],
        ),
    ]
