# Generated by Django 4.1.3 on 2022-11-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoloc', '0003_currentlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
